import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  Locale _locale = const Locale('pt');
  Locale get locale => _locale;

  void setLocale(Locale locale) {
    if (!['en', 'es', 'pt'].contains(locale.languageCode)) return;
    _locale = locale;
    notifyListeners();
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'SMART FEEDER',
      'welcome_back': 'WELCOME BACK',
      'pet_overview': 'Pet Overview',
      'water_level': 'WATER LEVEL',
      'food_weight': 'FOOD WEIGHT',
      'last_pet': 'LAST PET',
      'quick_actions': 'QUICK ACTIONS',
      'feed_now': 'FEED NOW',
      'tare_scale': 'TARE SCALE',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'history': 'History',
      'settings': 'Settings',
      'language': 'Language',
      'logout': 'Logout',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'register': 'Register',
      'no_account': 'Don\'t have an account?',
      'forgot_password': 'Forgot Password?',
      'feeding_triggered': 'Feeding Triggered',
      'scale_tared': 'Scale Tared Successfully',
      'new_pet_detected': 'NEW PET DETECTED!',
      'pet_name': 'Pet Name',
      'cancel': 'CANCEL',
      'save': 'SAVE',
      'loading': 'Loading...',
      'starting': 'Starting...',
      'disconnected': 'Disconnected',
      'calibrate_scale': 'Calibrate Scale',
      'calibration_step_1': 'Step 1: Empty the scale and press Tare.',
      'calibration_step_2': 'Step 2: Place a known weight and enter its value in grams.',
      'calibration_step_3': 'Step 3: Click Calibrate.',
      'known_weight': 'Known Weight (g)',
      'calibrate': 'Calibrate',
      'calibration_started': 'Calibration Started',
      'manual_factor': 'Manual Factor',
      'current_raw': 'Current Raw Value',
      'apply_factor': 'Apply Factor',
      'pet_insights': 'PET INSIGHTS',
      'no_pets': 'NO PETS REGISTERED',
      'view_insights': 'VIEW INSIGHTS',
      'simulate_health_alert': 'SIMULATE HEALTH ALERT',
      'weekly_trend_food': 'WEEKLY TREND: FOOD (g)',
      'weekly_trend_water': 'WEEKLY TREND: WATER (%)',
      'unknown': 'UNKNOWN',
      'food_consumption': 'FOOD CONSUMPTION',
      'water_hydration': 'HYDRATION (WATER)',
      'daily_monitoring': 'Daily monitoring of {type}. Current status is {status} based on the last 24 hours. Keep tracking for more health insights.',
      'no_history': 'NO HISTORY YET',
      'today': 'TODAY',
      'yesterday': 'YESTERDAY',
      'food': 'food',
      'water': 'water',
      'status_on_track': 'ON TRACK',
      'status_waiting': 'WAITING...',
      'status_below': 'BELOW TARGET',
      'status_above': 'ABOVE TARGET',
      'status_normal': 'NORMAL',
      'dashboard': 'Dashboard',
      'appearance': 'APPEARANCE',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Toggle between dark and light themes',
      'account': 'ACCOUNT',
      'profile_info': 'Profile Information',
      'profile_info_desc': 'View and edit your profile',
      'notifications': 'Notifications',
      'notifications_desc': 'Configure alerts and sounds',
      'developer': 'DEVELOPER',
      'seed_data': 'Seed Test Data',
      'seed_data_desc': 'Add mock pets and history to Firebase',
      'seed_success': 'Database Seeded Successfully!',
      'danger_zone': 'DANGER ZONE',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently remove your account',
      'alert_no_food': 'Has not eaten for {hours} hours. This could be a sign of illness.',
      'alert_no_water': 'Has not consumed water for {hours} hours. Check for signs of dehydration.',
    },
    'pt': {
      'app_name': 'ALIMENTADOR SMART',
      'welcome_back': 'BEM-VINDO DE VOLTA',
      'pet_overview': 'Visão Geral do Pet',
      'water_level': 'NÍVEL DE ÁGUA',
      'food_weight': 'PESO DA COMIDA',
      'last_pet': 'ÚLTIMO PET',
      'quick_actions': 'AÇÕES RÁPIDAS',
      'feed_now': 'ALIMENTAR AGORA',
      'tare_scale': 'TARAR BALANÇA',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'history': 'Histórico',
      'settings': 'Configurações',
      'language': 'Idioma',
      'logout': 'Sair',
      'login': 'Entrar',
      'email': 'E-mail',
      'password': 'Senha',
      'register': 'Cadastrar',
      'no_account': 'Não tem uma conta?',
      'forgot_password': 'Esqueceu a senha?',
      'feeding_triggered': 'Alimentação Acionada',
      'scale_tared': 'Balança Tarada com Sucesso',
      'new_pet_detected': 'NOVO PET DETECTADO!',
      'pet_name': 'Nome do Pet',
      'cancel': 'CANCELAR',
      'save': 'SALVAR',
      'loading': 'Carregando...',
      'starting': 'Iniciando...',
      'disconnected': 'Desconectado',
      'calibrate_scale': 'Calibrar Balança',
      'calibration_step_1': 'Passo 1: Esvazie a balança e aperte em Tarar.',
      'calibration_step_2': 'Passo 2: Coloque um peso conhecido e digite o valor em gramas.',
      'calibration_step_3': 'Passo 3: Clique em Calibrar.',
      'known_weight': 'Peso Conhecido (g)',
      'calibrate': 'Calibrar',
      'calibration_started': 'Calibração Iniciada',
      'manual_factor': 'Fator Manual',
      'current_raw': 'Valor Bruto Atual',
      'apply_factor': 'Aplicar Fator',
      'pet_insights': 'PET INSIGHTS',
      'no_pets': 'NENHUM PET CADASTRADO',
      'view_insights': 'VER INSIGHTS',
      'simulate_health_alert': 'SIMULAR ALERTA DE SAÚDE',
      'weekly_trend_food': 'TENDÊNCIA SEMANAL: COMIDA (g)',
      'weekly_trend_water': 'TENDÊNCIA SEMANAL: ÁGUA (%)',
      'unknown': 'DESCONHECIDO',
      'food_consumption': 'CONSUMO DE ALIMENTO',
      'water_hydration': 'HIDRATAÇÃO (ÁGUA)',
      'daily_monitoring': 'Monitoramento diário de {type}. O status atual é {status} baseado nas últimas 24 horas. Continue acompanhando para mais insights de saúde.',
      'no_history': 'SEM HISTÓRICO AINDA',
      'today': 'HOJE',
      'yesterday': 'ONTEM',
      'food': 'comida',
      'water': 'água',
      'status_on_track': 'NA META',
      'status_waiting': 'AGUARDANDO...',
      'status_below': 'ABOVE DA META',
      'status_above': 'ACIMA DA META',
      'status_normal': 'NORMAL',
      'dashboard': 'Painel',
      'appearance': 'APARÊNCIA',
      'dark_mode': 'Modo Escuro',
      'dark_mode_desc': 'Alternar entre temas claro e escuro',
      'account': 'CONTA',
      'profile_info': 'Informações do Perfil',
      'profile_info_desc': 'Visualizar e editar seu perfil',
      'notifications': 'Notificações',
      'notifications_desc': 'Configurar alertas e sons',
      'developer': 'DESENVOLVEDOR',
      'seed_data': 'Semear Dados de Teste',
      'seed_data_desc': 'Adicionar pets e histórico fictícios ao Firebase',
      'seed_success': 'Banco de Dados Semeado com Sucesso!',
      'danger_zone': 'ZONA DE PERIGO',
      'delete_account': 'Excluir Conta',
      'delete_account_desc': 'Remover permanentemente sua conta',
      'alert_no_food': 'Não come há {hours} horas. Isso pode ser um sinal de mal-estar.',
      'alert_no_water': 'Não consome água há {hours} horas. Verifique sinais de desidratação.',
    },
    'es': {
      'app_name': 'ALIMENTADOR SMART',
      'welcome_back': 'BIENVENIDO DE NUEVO',
      'pet_overview': 'Resumen de Mascota',
      'water_level': 'NIVEL DE AGUA',
      'food_weight': 'PESO DE COMIDA',
      'last_pet': 'ÚLTIMA MASCOTA',
      'quick_actions': 'ACCIONES RÁPIDAS',
      'feed_now': 'ALIMENTAR AHORA',
      'tare_scale': 'TARA DE BÁSCULA',
      'online': 'EN LÍNEA',
      'offline': 'DESCONECTADO',
      'history': 'Historial',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'logout': 'Cerrar Sesión',
      'login': 'Iniciar Sesión',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'register': 'Registrarse',
      'no_account': '¿No tienes una cuenta?',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'feeding_triggered': 'Alimentación Activada',
      'scale_tared': 'Báscula Tarada con Éxito',
      'new_pet_detected': '¡NUEVA MASCOTA DETECTADA!',
      'pet_name': 'Nombre de la Mascota',
      'cancel': 'CANCELAR',
      'save': 'GUARDAR',
      'loading': 'Cargando...',
      'starting': 'Iniciando...',
      'disconnected': 'Desconectado',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }
}
